# Generated by Django 5.2.5 on 2025-08-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_jobhistory_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobhistory",
            name="alternative_names",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
