# Generated by Django 5.2.5 on 2025-08-20 09:31

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_userfeedback"),
    ]

    operations = [
        VectorExtension(),
    ]
