# Generated by Django 5.2.5 on 2025-08-20 09:32

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_auto_20250820_0931"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Career Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedNarrative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "narrative_type",
                    models.CharField(
                        choices=[
                            ("cover_letter", "Cover Letter"),
                            ("summary", "Professional Summary"),
                            ("motivation", "Motivation Statement"),
                            ("value_proposition", "Value Proposition"),
                        ],
                        max_length=30,
                    ),
                ),
                ("content", models.TextField()),
                ("generation_prompt", models.TextField(blank=True)),
                (
                    "ai_model_used",
                    models.CharField(default="openai/gpt-5-chat", max_length=100),
                ),
                ("user_feedback", models.TextField(blank=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "searched_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_narratives",
                        to="jobs.searchedjob",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_narratives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PersonalInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("company_motivation", "Why This Company"),
                            ("career_motivation", "Career Motivation"),
                            ("leadership_style", "Leadership Approach"),
                            ("work_values", "Professional Values"),
                            ("unique_value", "Unique Value Proposition"),
                            ("industry_knowledge", "Industry Insights"),
                            ("problem_solving", "Problem Solving Approach"),
                            ("team_building", "Team Building Philosophy"),
                            ("change_management", "Change Management Style"),
                            ("technical_vision", "Technical Vision"),
                        ],
                        max_length=50,
                    ),
                ),
                ("question", models.TextField()),
                ("content", models.TextField()),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="jobs.careercategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "category", "insight_type")},
            },
        ),
        migrations.CreateModel(
            name="NarrativeInsightUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usage_weight", models.FloatField()),
                ("specific_content", models.TextField(blank=True)),
                (
                    "narrative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.generatednarrative",
                    ),
                ),
                (
                    "insight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.personalinsight",
                    ),
                ),
            ],
            options={
                "unique_together": {("narrative", "insight")},
            },
        ),
        migrations.AddField(
            model_name="generatednarrative",
            name="insights_used",
            field=models.ManyToManyField(
                through="jobs.NarrativeInsightUsage", to="jobs.personalinsight"
            ),
        ),
        migrations.CreateModel(
            name="JobInsightMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relevance_score", models.FloatField()),
                ("category_match_bonus", models.FloatField(default=0.0)),
                ("final_score", models.FloatField()),
                ("is_used_in_narrative", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "searched_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight_matches",
                        to="jobs.searchedjob",
                    ),
                ),
                (
                    "matched_insight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_matches",
                        to="jobs.personalinsight",
                    ),
                ),
            ],
            options={
                "ordering": ["-final_score"],
                "unique_together": {("searched_job", "matched_insight")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="generatednarrative",
            unique_together={("searched_job", "narrative_type")},
        ),
    ]
